services:
  db:
    image: "postgres:15"
    ports:
      - "5434:5432"
    environment:
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: api


  api:
    build:
      context: .
    ports:
      - "3000:3000"       